# Theoretical Foundations of BS3008

This week's (i.e., week 1) lecture aims to provide an introduction to BS3008's course contents by explaining its various theoretical aspects.

## Discplines in BS3008

BS3008 covers numerous disciplines, including the following. A brief explanation on what each discipline is is also provided for each of the disciplines:

1.  **Chemoinformatics**

    This discipline deals with similarities and differences between chemical compounds.

    Chemoinformatics deals with compounds from $10^{-60}$ to $10^{-30}$ in magnitudes. Individuals who work in this field try to find "an island in an ocean" - they try to find a molecule that can do *some* purpose.

2.  **Bioinformatics**

    This disciplines applies informatics tools (e.g., Python coding) to Biological molecules and data.

    Bioinformatics mainly focuses on Biological modelling.

3.  **Theoretical Chemistry (i.e., Quantum Chemistry)**

    This discipline provides the theoretical foundations needed to understand the course's contents.

4.  **Computational Chemistry and Biology**

    This discipline not only encompasses theoretical chemistry, but also molecular mechanics, minimization, simulations, and conformational analysis.

5.  **Molecular Modelling**

    This discipline uses all of the above disciplines to represent and manipulate the structures of molecules.

    This also means that this discipline uses physics to model a system - that way, a model can be compared against experimental results.

Hence, BS3008 primarily focuses on molecular modelling (with emphasis on theoretical chemistry for the theoretical component of the course).

### What is Molecular Modelling?

According to Tamar Schlick, molecular modelling is:

> "...the science and art of studying molecular structure and function through model building and computation."
>
> -- Tamar Schlick

"Computation" in this sense refer to practices such as:

1.  ab initio and semi-empirical quantum mechanics
2.  Molecular mechanics
3.  Monte Carlo simulations
4.  Molecular dynamics
5.  Free energy and solvation methods
6.  Structure / activity relationships (i.e., SAR analyses)
7.  Chemical / biochemical information and databases

It is important to understand that while "model building" can be as simple as using plastic or metal rods to depict molecules' structures, it can also be as sophisticated as an interactive, animated color graphics and lasers.

Nonetheless, the computational tools used in molecular modelling is just as, if not more complex than Biological systems. However, the concepts in molecular modelling must be carefully applied and one must also be wary of molecular modeling's strengths and weaknesses.

### Important Databases and Tools

Professor Mu lists some important molecular modelling tools in this chapter - click on their hyperlinks to access them:

1.  [**PDB**](https://www.rcsb.org/)

    This is a database with numerous entries on proteins' information.

2.  [**PDBBinding**](http://pdbbind.org.cn/)

    This is another database that provides entries on the binding affinity for all biomolecular complexes.

3.  [**ZINK DOCK**]()

    <this site appears to be down>

4.  [**Autodock Zina**](https://vina.scripps.edu/)

    This is an open-source program for performing molecular docking.
<<<<<<< HEAD

## Professor Mu's Current Works

As of the time of writing, professor Mu's lab is currently focused on the following topics:

1.  Amyloidogenic protein / peptide aggregation and misfolding
2.  DNA-DNA, DNA-ions, and DNA-protein interactions
3.  Drug-protein interaction and drug candidate screening
4.  Peptide-membrane interactions.

For more information on professor Mu's current research topics, do visit his [lab's homepage](https://www.ntu.edu.sg/sbs/research/research-directory/Mu-Yuguang).
=======
>>>>>>> 0eff75b34526bcaa96a054174575c32a54ab15bc
